appName: opendaoc-database
namespace: prod
replicaCount: 3
image:
  name: ghcr.io/gz-42/opendaoc-database
  tag: 2025.11.15
storageClassName: gp3
#MARIADB_ROOT_PASSWORD: bXktc2VjcmV0LXB3
# echo -n 'my-secret-pw' | base64
